/* eslint-disable no-undef */

/****************************************************
 *  PhyUnit.js
 *  自动生成的物理单位 Temml 宏定义
 ****************************************************/

function preprocessLatexUnits(latex) {
    const unitCommands = ['UatmLmolK', 'UAcdots', 'UJcdots', 'Ukgmqsq', 'UNmqkgq', 'UNcdotm', 'Uradmin', 'UJkgdC', 'UJmolK', 'Ukgmol', 'Ukgmsq', 'Umcmol', 'Umolnc', 'Umolnq', 'UNmqCq', 'Uspace', 'UCmol', 'Ucmsq', 'UJcal', 'UJkgK', 'Ukgmc', 'Ukgms', 'UkJkg', 'Ukmsq', 'ULmol', 'UmmHg', 'UcmHg', 'Umoln', 'UWbmq', 'Urads', 'Urmin', 'Uatm', 'Ucal', 'UduC', 'UCkg', 'Ucmc', 'Ucmq', 'Ucms', 'Udmc', 'Udyn', 'Uerg', 'UImA', 'UJkg', 'UkgC', 'Ukgf', 'Ukgs', 'UkHz', 'Ukmh', 'Ukms', 'Umcs', 'UMeV', 'UMHz', 'Ummc', 'Ummq', 'Umnc', 'Umnq', 'Umol', 'Umsq', 'UNAq', 'UNkg', 'UNmq', 'UNcm', 'UsVC', 'UTmq', 'UVsA', 'UWbs', 'UWmq', 'Umin', 'UkPa', 'Uimp', 'Urad', 'UkWh', 'UmAh', 'UAi', 'UAm', 'UAs', 'UdC', 'Ucm', 'UCV', 'UdB', 'Udm', 'UeV', 'UHP', 'UHs', 'UHz', 'UJC', 'UJs', 'Ukg', 'UkO', 'UkW', 'Umc', 'UmH', 'Umm', 'Umn', 'UMO', 'Umq', 'Ums', 'Uum', 'UNC', 'UnF', 'UNm', 'UNs', 'UOm', 'UOs', 'UPa', 'UpF', 'UsF', 'Usq', 'Usn', 'UuA', 'UmA', 'UuF', 'UuH', 'UVm', 'UVA', 'UWb', 'UmL', 'Unm', 'Ukm', 'UkV', 'UkJ', 'Urs', 'UAU', 'Ucd', 'UA', 'UC', 'Ue', 'UF', 'Ug', 'UH', 'UJ', 'UK', 'UL', 'Um', 'UN', 'UO', 'Us', 'UT', 'Uu', 'UV', 'UW', 'Uh', 'Ut'];

    unitCommands.forEach(cmd => {
        // 步骤1: 替换 \cmd[a] 为 \cmd@a
        latex = latex.replace(new RegExp(`\\\\${cmd}\\s*\\[a\\]`, 'g'), `\\${cmd}@a`);

        // 步骤2: 替换 \cmd[其他] 为 \cmd@default
        latex = latex.replace(new RegExp(`\\\\${cmd}\\s*\\[[^\\]]*\\]`, 'g'), `\\${cmd}@default`);

        // 步骤3: 替换裸命令 \cmd 为 \cmd@default
        latex = latex.replace(new RegExp(`\\\\${cmd}(?![a-zA-Z]|@)`, 'g'), `\\${cmd}@default`);
    });

    return latex;
}

/****************************************************
 *  宏定义
 ****************************************************/
temml.__defineMacro("\\UatmLmolK@default", "{\\;\\mathrm{atm}\\cdot\\mathrm{L}/(\\mathrm{mol}\\cdot\\mathrm{K})}");
temml.__defineMacro("\\UatmLmolK@a", "{\\mathrm{atm}\\cdot\\mathrm{L}/(\\mathrm{mol}\\cdot\\mathrm{K})}");
temml.__defineMacro("\\UAcdots@default", "{\\;\\mathrm{A}\\cdot\\mathrm{s}}");
temml.__defineMacro("\\UAcdots@a", "{\\mathrm{A}\\cdot\\mathrm{s}}");
temml.__defineMacro("\\UJcdots@default", "{\\;\\mathrm{J}\\cdot\\mathrm{s}}");
temml.__defineMacro("\\UJcdots@a", "{\\mathrm{J}\\cdot\\mathrm{s}}");
temml.__defineMacro("\\Ukgmqsq@default", "{\\;\\mathrm{kg}\\cdot\\mathrm{m}^2\\cdot\\mathrm{s}^{-2}}");
temml.__defineMacro("\\Ukgmqsq@a", "{\\mathrm{kg}\\cdot\\mathrm{m}^2\\cdot\\mathrm{s}^{-2}}");
temml.__defineMacro("\\UNmqkgq@default", "{\\;\\mathrm{N}\\cdot\\mathrm{m}^2/\\mathrm{kg}^2}");
temml.__defineMacro("\\UNmqkgq@a", "{\\mathrm{N}\\cdot\\mathrm{m}^2/\\mathrm{kg}^2}");
temml.__defineMacro("\\UNcdotm@default", "{\\;\\mathrm{N}\\cdot\\mathrm{m}}");
temml.__defineMacro("\\UNcdotm@a", "{\\mathrm{N}\\cdot\\mathrm{m}}");
temml.__defineMacro("\\Uradmin@default", "{\\;\\mathrm{rad}/\\mathrm{min}}");
temml.__defineMacro("\\Uradmin@a", "{\\mathrm{rad}/\\mathrm{min}}");
temml.__defineMacro("\\UJkgdC@default", "{\\;\\mathrm{J}/(\\mathrm{kg}\\cdot{}^\\circ\\mathrm{C})}");
temml.__defineMacro("\\UJkgdC@a", "{\\mathrm{J}/(\\mathrm{kg}\\cdot{}^\\circ\\mathrm{C})}");
temml.__defineMacro("\\UJmolK@default", "{\\;\\mathrm{J}/(\\mathrm{mol}\\cdot\\mathrm{K})}");
temml.__defineMacro("\\UJmolK@a", "{\\mathrm{J}/(\\mathrm{mol}\\cdot\\mathrm{K})}");
temml.__defineMacro("\\Ukgmol@default", "{\\;\\mathrm{kg}/\\mathrm{mol}}");
temml.__defineMacro("\\Ukgmol@a", "{\\mathrm{kg}/\\mathrm{mol}}");
temml.__defineMacro("\\Ukgmsq@default", "{\\;\\mathrm{kg}\\cdot\\mathrm{m}/\\mathrm{s}^2}");
temml.__defineMacro("\\Ukgmsq@a", "{\\mathrm{kg}\\cdot\\mathrm{m}/\\mathrm{s}^2}");
temml.__defineMacro("\\Umcmol@default", "{\\;\\mathrm{m}^3/\\mathrm{mol}}");
temml.__defineMacro("\\Umcmol@a", "{\\mathrm{m}^3/\\mathrm{mol}}");
temml.__defineMacro("\\Umolnc@default", "{\\;\\mathrm{mol}^{-3}} % mol^{-3}");
temml.__defineMacro("\\Umolnc@a", "{\\mathrm{mol}^{-3}} % mol^{-3}");
temml.__defineMacro("\\Umolnq@default", "{\\;\\mathrm{mol}^{-2}} % mol^{-2}");
temml.__defineMacro("\\Umolnq@a", "{\\mathrm{mol}^{-2}} % mol^{-2}");
temml.__defineMacro("\\UNmqCq@default", "{\\;\\mathrm{N}\\cdot\\mathrm{m}^2/\\mathrm{C}^2}");
temml.__defineMacro("\\UNmqCq@a", "{\\mathrm{N}\\cdot\\mathrm{m}^2/\\mathrm{C}^2}");
temml.__defineMacro("\\Uspace@default", "{\\;}");
temml.__defineMacro("\\Uspace@a", "{}");
temml.__defineMacro("\\UCmol@default", "{\\;\\mathrm{C}/\\mathrm{mol}}");
temml.__defineMacro("\\UCmol@a", "{\\mathrm{C}/\\mathrm{mol}}");
temml.__defineMacro("\\Ucmsq@default", "{\\;\\mathrm{cm}/\\mathrm{s}^2}");
temml.__defineMacro("\\Ucmsq@a", "{\\mathrm{cm}/\\mathrm{s}^2}");
temml.__defineMacro("\\UJcal@default", "{\\;\\mathrm{J}/\\mathrm{cal}}");
temml.__defineMacro("\\UJcal@a", "{\\mathrm{J}/\\mathrm{cal}}");
temml.__defineMacro("\\UJkgK@default", "{\\;\\mathrm{J}/(\\mathrm{kg}\\cdot\\mathrm{K})}");
temml.__defineMacro("\\UJkgK@a", "{\\mathrm{J}/(\\mathrm{kg}\\cdot\\mathrm{K})}");
temml.__defineMacro("\\Ukgmc@default", "{\\;\\mathrm{kg}/\\mathrm{m}^3}");
temml.__defineMacro("\\Ukgmc@a", "{\\mathrm{kg}/\\mathrm{m}^3}");
temml.__defineMacro("\\Ukgms@default", "{\\;\\mathrm{kg}\\cdot\\mathrm{m}/\\mathrm{s}}");
temml.__defineMacro("\\Ukgms@a", "{\\mathrm{kg}\\cdot\\mathrm{m}/\\mathrm{s}}");
temml.__defineMacro("\\UkJkg@default", "{\\;\\mathrm{kJ}/\\mathrm{kg}}");
temml.__defineMacro("\\UkJkg@a", "{\\mathrm{kJ}/\\mathrm{kg}}");
temml.__defineMacro("\\Ukmsq@default", "{\\;\\mathrm{km}/\\mathrm{s}^2}");
temml.__defineMacro("\\Ukmsq@a", "{\\mathrm{km}/\\mathrm{s}^2}");
temml.__defineMacro("\\ULmol@default", "{\\;\\mathrm{L}/\\mathrm{mol}}");
temml.__defineMacro("\\ULmol@a", "{\\mathrm{L}/\\mathrm{mol}}");
temml.__defineMacro("\\UmmHg@default", "{\\;\\mathrm{mmHg}}");
temml.__defineMacro("\\UmmHg@a", "{\\mathrm{mmHg}}");
temml.__defineMacro("\\UcmHg@default", "{\\;\\mathrm{cmHg}}");
temml.__defineMacro("\\UcmHg@a", "{\\mathrm{cmHg}}");
temml.__defineMacro("\\Umoln@default", "{\\;\\mathrm{mol}^{-1}} % mol^{-1}");
temml.__defineMacro("\\Umoln@a", "{\\mathrm{mol}^{-1}} % mol^{-1}");
temml.__defineMacro("\\UWbmq@default", "{\\;\\mathrm{Wb}/\\mathrm{m}^2}");
temml.__defineMacro("\\UWbmq@a", "{\\mathrm{Wb}/\\mathrm{m}^2}");
temml.__defineMacro("\\Urads@default", "{\\;\\mathrm{rad}/\\mathrm{s}}");
temml.__defineMacro("\\Urads@a", "{\\mathrm{rad}/\\mathrm{s}}");
temml.__defineMacro("\\Urmin@default", "{\\;\\mathrm{r}/\\mathrm{min}}");
temml.__defineMacro("\\Urmin@a", "{\\mathrm{r}/\\mathrm{min}}");
temml.__defineMacro("\\Uatm@default", "{\\;\\mathrm{atm}}");
temml.__defineMacro("\\Uatm@a", "{\\mathrm{atm}}");
temml.__defineMacro("\\Ucal@default", "{\\;\\mathrm{cal}}");
temml.__defineMacro("\\Ucal@a", "{\\mathrm{cal}}");
temml.__defineMacro("\\UduC@default", "{\\;{}^\\circ\\mathrm{C}}");
temml.__defineMacro("\\UduC@a", "{{}^\\circ\\mathrm{C}}");
temml.__defineMacro("\\UCkg@default", "{\\;\\mathrm{C}/\\mathrm{kg}}");
temml.__defineMacro("\\UCkg@a", "{\\mathrm{C}/\\mathrm{kg}}");
temml.__defineMacro("\\Ucmc@default", "{\\;\\mathrm{cm}^3}");
temml.__defineMacro("\\Ucmc@a", "{\\mathrm{cm}^3}");
temml.__defineMacro("\\Ucmq@default", "{\\;\\mathrm{cm}^2}");
temml.__defineMacro("\\Ucmq@a", "{\\mathrm{cm}^2}");
temml.__defineMacro("\\Ucms@default", "{\\;\\mathrm{cm}/\\mathrm{s}}");
temml.__defineMacro("\\Ucms@a", "{\\mathrm{cm}/\\mathrm{s}}");
temml.__defineMacro("\\Udmc@default", "{\\;\\mathrm{dm}^3}");
temml.__defineMacro("\\Udmc@a", "{\\mathrm{dm}^3}");
temml.__defineMacro("\\Udyn@default", "{\\;\\mathrm{dyn}}");
temml.__defineMacro("\\Udyn@a", "{\\mathrm{dyn}}");
temml.__defineMacro("\\Uerg@default", "{\\;\\mathrm{erg}}");
temml.__defineMacro("\\Uerg@a", "{\\mathrm{erg}}");
temml.__defineMacro("\\UImA@default", "{\\;\\mathrm{mA}}");
temml.__defineMacro("\\UImA@a", "{\\mathrm{mA}}");
temml.__defineMacro("\\UJkg@default", "{\\;\\mathrm{J}/\\mathrm{kg}}");
temml.__defineMacro("\\UJkg@a", "{\\mathrm{J}/\\mathrm{kg}}");
temml.__defineMacro("\\UkgC@default", "{\\;\\mathrm{kg}/\\mathrm{C}}");
temml.__defineMacro("\\UkgC@a", "{\\mathrm{kg}/\\mathrm{C}}");
temml.__defineMacro("\\Ukgf@default", "{\\;\\mathrm{kgf}}");
temml.__defineMacro("\\Ukgf@a", "{\\mathrm{kgf}}");
temml.__defineMacro("\\Ukgs@default", "{\\;\\mathrm{kg}/\\mathrm{s}}");
temml.__defineMacro("\\Ukgs@a", "{\\mathrm{kg}/\\mathrm{s}}");
temml.__defineMacro("\\UkHz@default", "{\\;\\mathrm{kHz}}");
temml.__defineMacro("\\UkHz@a", "{\\mathrm{kHz}}");
temml.__defineMacro("\\Ukmh@default", "{\\;\\mathrm{km}/\\mathrm{h}}");
temml.__defineMacro("\\Ukmh@a", "{\\mathrm{km}/\\mathrm{h}}");
temml.__defineMacro("\\Ukms@default", "{\\;\\mathrm{km}/\\mathrm{s}}");
temml.__defineMacro("\\Ukms@a", "{\\mathrm{km}/\\mathrm{s}}");
temml.__defineMacro("\\Umcs@default", "{\\;\\mathrm{m}^3/\\mathrm{s}}");
temml.__defineMacro("\\Umcs@a", "{\\mathrm{m}^3/\\mathrm{s}}");
temml.__defineMacro("\\UMeV@default", "{\\;\\mathrm{MeV}}");
temml.__defineMacro("\\UMeV@a", "{\\mathrm{MeV}}");
temml.__defineMacro("\\UMHz@default", "{\\;\\mathrm{MHz}}");
temml.__defineMacro("\\UMHz@a", "{\\mathrm{MHz}}");
temml.__defineMacro("\\Ummc@default", "{\\;\\mathrm{mm}^3}");
temml.__defineMacro("\\Ummc@a", "{\\mathrm{mm}^3}");
temml.__defineMacro("\\Ummq@default", "{\\;\\mathrm{mm}^2}");
temml.__defineMacro("\\Ummq@a", "{\\mathrm{mm}^2}");
temml.__defineMacro("\\Umnc@default", "{\\;\\mathrm{m}^{-3}} % m^{-3}");
temml.__defineMacro("\\Umnc@a", "{\\mathrm{m}^{-3}} % m^{-3}");
temml.__defineMacro("\\Umnq@default", "{\\;\\mathrm{m}^{-2}} % m^{-2}");
temml.__defineMacro("\\Umnq@a", "{\\mathrm{m}^{-2}} % m^{-2}");
temml.__defineMacro("\\Umol@default", "{\\;\\mathrm{mol}}");
temml.__defineMacro("\\Umol@a", "{\\mathrm{mol}}");
temml.__defineMacro("\\Umsq@default", "{\\;\\mathrm{m}/\\mathrm{s}^2}");
temml.__defineMacro("\\Umsq@a", "{\\mathrm{m}/\\mathrm{s}^2}");
temml.__defineMacro("\\UNAq@default", "{\\;\\mathrm{N}/\\mathrm{A}^2}");
temml.__defineMacro("\\UNAq@a", "{\\mathrm{N}/\\mathrm{A}^2}");
temml.__defineMacro("\\UNkg@default", "{\\;\\mathrm{N}/\\mathrm{kg}}");
temml.__defineMacro("\\UNkg@a", "{\\mathrm{N}/\\mathrm{kg}}");
temml.__defineMacro("\\UNmq@default", "{\\;\\mathrm{N}/\\mathrm{m}^2}");
temml.__defineMacro("\\UNmq@a", "{\\mathrm{N}/\\mathrm{m}^2}");
temml.__defineMacro("\\UNcm@default", "{\\;\\mathrm{N}/\\mathrm{cm}}");
temml.__defineMacro("\\UNcm@a", "{\\mathrm{N}/\\mathrm{cm}}");
temml.__defineMacro("\\UsVC@default", "{\\;\\mathrm{s}\\cdot\\mathrm{V}/\\mathrm{C}}");
temml.__defineMacro("\\UsVC@a", "{\\mathrm{s}\\cdot\\mathrm{V}/\\mathrm{C}}");
temml.__defineMacro("\\UTmq@default", "{\\;\\mathrm{T}\\cdot\\mathrm{m}^2}");
temml.__defineMacro("\\UTmq@a", "{\\mathrm{T}\\cdot\\mathrm{m}^2}");
temml.__defineMacro("\\UVsA@default", "{\\;\\mathrm{V}\\cdot\\mathrm{s}/\\mathrm{A}}");
temml.__defineMacro("\\UVsA@a", "{\\mathrm{V}\\cdot\\mathrm{s}/\\mathrm{A}}");
temml.__defineMacro("\\UWbs@default", "{\\;\\mathrm{Wb}/\\mathrm{s}}");
temml.__defineMacro("\\UWbs@a", "{\\mathrm{Wb}/\\mathrm{s}}");
temml.__defineMacro("\\UWmq@default", "{\\;\\mathrm{W}/\\mathrm{m}^2}");
temml.__defineMacro("\\UWmq@a", "{\\mathrm{W}/\\mathrm{m}^2}");
temml.__defineMacro("\\Umin@default", "{\\;\\mathrm{min}}");
temml.__defineMacro("\\Umin@a", "{\\mathrm{min}}");
temml.__defineMacro("\\UkPa@default", "{\\;\\mathrm{kPa}}");
temml.__defineMacro("\\UkPa@a", "{\\mathrm{kPa}}");
temml.__defineMacro("\\Uimp@default", "{\\;\\mathrm{imp}}");
temml.__defineMacro("\\Uimp@a", "{\\mathrm{imp}}");
temml.__defineMacro("\\Urad@default", "{\\;\\mathrm{rad}}");
temml.__defineMacro("\\Urad@a", "{\\mathrm{rad}}");
temml.__defineMacro("\\UkWh@default", "{\\;\\mathrm{kW}\\cdot\\mathrm{h}}");
temml.__defineMacro("\\UkWh@a", "{\\mathrm{kW}\\cdot\\mathrm{h}}");
temml.__defineMacro("\\UmAh@default", "{\\;\\mathrm{mA}\\cdot\\mathrm{h}}");
temml.__defineMacro("\\UmAh@a", "{\\mathrm{mA}\\cdot\\mathrm{h}}");
temml.__defineMacro("\\UAi@default", "{\\;\\mathrm{\\AA}}");
temml.__defineMacro("\\UAi@a", "{\\mathrm{\\AA}}");
temml.__defineMacro("\\UAm@default", "{\\;\\mathrm{A}\\cdot\\mathrm{m}}");
temml.__defineMacro("\\UAm@a", "{\\mathrm{A}\\cdot\\mathrm{m}}");
temml.__defineMacro("\\UAs@default", "{\\;\\mathrm{A}/\\mathrm{s}}");
temml.__defineMacro("\\UAs@a", "{\\mathrm{A}/\\mathrm{s}}");
temml.__defineMacro("\\UdC@default", "{\\;{}^\\circ\\mathrm{C}}");
temml.__defineMacro("\\UdC@a", "{{}^\\circ\\mathrm{C}}");
temml.__defineMacro("\\Ucm@default", "{\\;\\mathrm{cm}}");
temml.__defineMacro("\\Ucm@a", "{\\mathrm{cm}}");
temml.__defineMacro("\\UCV@default", "{\\;\\mathrm{C}/\\mathrm{V}}");
temml.__defineMacro("\\UCV@a", "{\\mathrm{C}/\\mathrm{V}}");
temml.__defineMacro("\\UdB@default", "{\\;\\mathrm{dB}}");
temml.__defineMacro("\\UdB@a", "{\\mathrm{dB}}");
temml.__defineMacro("\\Udm@default", "{\\;\\mathrm{dm}}");
temml.__defineMacro("\\Udm@a", "{\\mathrm{dm}}");
temml.__defineMacro("\\UeV@default", "{\\;\\mathrm{eV}}");
temml.__defineMacro("\\UeV@a", "{\\mathrm{eV}}");
temml.__defineMacro("\\UHP@default", "{\\;\\mathrm{HP}}");
temml.__defineMacro("\\UHP@a", "{\\mathrm{HP}}");
temml.__defineMacro("\\UHs@default", "{\\;\\mathrm{H}/\\mathrm{s}}");
temml.__defineMacro("\\UHs@a", "{\\mathrm{H}/\\mathrm{s}}");
temml.__defineMacro("\\UHz@default", "{\\;\\mathrm{Hz}}");
temml.__defineMacro("\\UHz@a", "{\\mathrm{Hz}}");
temml.__defineMacro("\\UJC@default", "{\\;\\mathrm{J}/\\mathrm{C}}");
temml.__defineMacro("\\UJC@a", "{\\mathrm{J}/\\mathrm{C}}");
temml.__defineMacro("\\UJs@default", "{\\;\\mathrm{J}/\\mathrm{s}}");
temml.__defineMacro("\\UJs@a", "{\\mathrm{J}/\\mathrm{s}}");
temml.__defineMacro("\\Ukg@default", "{\\;\\mathrm{kg}}");
temml.__defineMacro("\\Ukg@a", "{\\mathrm{kg}}");
temml.__defineMacro("\\UkO@default", "{\\;\\mathrm{k}\\Omega}");
temml.__defineMacro("\\UkO@a", "{\\mathrm{k}\\Omega}");
temml.__defineMacro("\\UkW@default", "{\\;\\mathrm{kW}}");
temml.__defineMacro("\\UkW@a", "{\\mathrm{kW}}");
temml.__defineMacro("\\Umc@default", "{\\;\\mathrm{m}^3}");
temml.__defineMacro("\\Umc@a", "{\\mathrm{m}^3}");
temml.__defineMacro("\\UmH@default", "{\\;\\mathrm{mH}}");
temml.__defineMacro("\\UmH@a", "{\\mathrm{mH}}");
temml.__defineMacro("\\Umm@default", "{\\;\\mathrm{mm}}");
temml.__defineMacro("\\Umm@a", "{\\mathrm{mm}}");
temml.__defineMacro("\\Umn@default", "{\\;\\mathrm{m}^{-1}} % m^{-1}");
temml.__defineMacro("\\Umn@a", "{\\mathrm{m}^{-1}} % m^{-1}");
temml.__defineMacro("\\UMO@default", "{\\;\\mathrm{M}\\Omega}");
temml.__defineMacro("\\UMO@a", "{\\mathrm{M}\\Omega}");
temml.__defineMacro("\\Umq@default", "{\\;\\mathrm{m}^2}");
temml.__defineMacro("\\Umq@a", "{\\mathrm{m}^2}");
temml.__defineMacro("\\Ums@default", "{\\;\\mathrm{m}/\\mathrm{s}}");
temml.__defineMacro("\\Ums@a", "{\\mathrm{m}/\\mathrm{s}}");
temml.__defineMacro("\\Uum@default", "{\\;\\mu\\mathrm{m}}");
temml.__defineMacro("\\Uum@a", "{\\mu\\mathrm{m}}");
temml.__defineMacro("\\UNC@default", "{\\;\\mathrm{N}/\\mathrm{C}}");
temml.__defineMacro("\\UNC@a", "{\\mathrm{N}/\\mathrm{C}}");
temml.__defineMacro("\\UnF@default", "{\\;\\mathrm{nF}}");
temml.__defineMacro("\\UnF@a", "{\\mathrm{nF}}");
temml.__defineMacro("\\UNm@default", "{\\;\\mathrm{N}/\\mathrm{m}}");
temml.__defineMacro("\\UNm@a", "{\\mathrm{N}/\\mathrm{m}}");
temml.__defineMacro("\\UNs@default", "{\\;\\mathrm{N}\\cdot\\mathrm{s}}");
temml.__defineMacro("\\UNs@a", "{\\mathrm{N}\\cdot\\mathrm{s}}");
temml.__defineMacro("\\UOm@default", "{\\;\\Omega\\cdot\\mathrm{m}}");
temml.__defineMacro("\\UOm@a", "{\\Omega\\cdot\\mathrm{m}}");
temml.__defineMacro("\\UOs@default", "{\\;\\Omega\\cdot\\mathrm{s}}");
temml.__defineMacro("\\UOs@a", "{\\Omega\\cdot\\mathrm{s}}");
temml.__defineMacro("\\UPa@default", "{\\;\\mathrm{Pa}}");
temml.__defineMacro("\\UPa@a", "{\\mathrm{Pa}}");
temml.__defineMacro("\\UpF@default", "{\\;\\mathrm{pF}}");
temml.__defineMacro("\\UpF@a", "{\\mathrm{pF}}");
temml.__defineMacro("\\UsF@default", "{\\;\\mathrm{s}/\\mathrm{F}}");
temml.__defineMacro("\\UsF@a", "{\\mathrm{s}/\\mathrm{F}}");
temml.__defineMacro("\\Usq@default", "{\\;\\mathrm{s}^2}");
temml.__defineMacro("\\Usq@a", "{\\mathrm{s}^2}");
temml.__defineMacro("\\Usn@default", "{\\;\\mathrm{s}^{-1}} % s^{-1}");
temml.__defineMacro("\\Usn@a", "{\\mathrm{s}^{-1}} % s^{-1}");
temml.__defineMacro("\\UuA@default", "{\\;\\mu\\mathrm{A}}");
temml.__defineMacro("\\UuA@a", "{\\mu\\mathrm{A}}");
temml.__defineMacro("\\UmA@default", "{\\;\\mathrm{mA}}");
temml.__defineMacro("\\UmA@a", "{\\mathrm{mA}}");
temml.__defineMacro("\\UuF@default", "{\\;\\mu\\mathrm{F}}");
temml.__defineMacro("\\UuF@a", "{\\mu\\mathrm{F}}");
temml.__defineMacro("\\UuH@default", "{\\;\\mu\\mathrm{H}}");
temml.__defineMacro("\\UuH@a", "{\\mu\\mathrm{H}}");
temml.__defineMacro("\\UVm@default", "{\\;\\mathrm{V}/\\mathrm{m}}");
temml.__defineMacro("\\UVm@a", "{\\mathrm{V}/\\mathrm{m}}");
temml.__defineMacro("\\UVA@default", "{\\;\\mathrm{V}/\\mathrm{A}}");
temml.__defineMacro("\\UVA@a", "{\\mathrm{V}/\\mathrm{A}}");
temml.__defineMacro("\\UWb@default", "{\\;\\mathrm{Wb}}");
temml.__defineMacro("\\UWb@a", "{\\mathrm{Wb}}");
temml.__defineMacro("\\UmL@default", "{\\;\\mathrm{mL}}");
temml.__defineMacro("\\UmL@a", "{\\mathrm{mL}}");
temml.__defineMacro("\\Unm@default", "{\\;\\mathrm{nm}}");
temml.__defineMacro("\\Unm@a", "{\\mathrm{nm}}");
temml.__defineMacro("\\Ukm@default", "{\\;\\mathrm{km}}");
temml.__defineMacro("\\Ukm@a", "{\\mathrm{km}}");
temml.__defineMacro("\\UkV@default", "{\\;\\mathrm{kV}}");
temml.__defineMacro("\\UkV@a", "{\\mathrm{kV}}");
temml.__defineMacro("\\UkJ@default", "{\\;\\mathrm{kJ}}");
temml.__defineMacro("\\UkJ@a", "{\\mathrm{kJ}}");
temml.__defineMacro("\\Urs@default", "{\\;\\mathrm{r}/\\mathrm{s}}");
temml.__defineMacro("\\Urs@a", "{\\mathrm{r}/\\mathrm{s}}");
temml.__defineMacro("\\UAU@default", "{\\;\\mathrm{AU}}");
temml.__defineMacro("\\UAU@a", "{\\mathrm{AU}}");
temml.__defineMacro("\\Ucd@default", "{\\;\\mathrm{cd}}");
temml.__defineMacro("\\Ucd@a", "{\\mathrm{cd}}");
temml.__defineMacro("\\UA@default", "{\\;\\mathrm{A}}");
temml.__defineMacro("\\UA@a", "{\\mathrm{A}}");
temml.__defineMacro("\\UC@default", "{\\;\\mathrm{C}}");
temml.__defineMacro("\\UC@a", "{\\mathrm{C}}");
temml.__defineMacro("\\Ue@default", "{\\;\\mathrm{e}}");
temml.__defineMacro("\\Ue@a", "{\\mathrm{e}}");
temml.__defineMacro("\\UF@default", "{\\;\\mathrm{F}}");
temml.__defineMacro("\\UF@a", "{\\mathrm{F}}");
temml.__defineMacro("\\Ug@default", "{\\;\\mathrm{g}}");
temml.__defineMacro("\\Ug@a", "{\\mathrm{g}}");
temml.__defineMacro("\\UH@default", "{\\;\\mathrm{H}}");
temml.__defineMacro("\\UH@a", "{\\mathrm{H}}");
temml.__defineMacro("\\UJ@default", "{\\;\\mathrm{J}}");
temml.__defineMacro("\\UJ@a", "{\\mathrm{J}}");
temml.__defineMacro("\\UK@default", "{\\;\\mathrm{K}}");
temml.__defineMacro("\\UK@a", "{\\mathrm{K}}");
temml.__defineMacro("\\UL@default", "{\\;\\mathrm{L}}");
temml.__defineMacro("\\UL@a", "{\\mathrm{L}}");
temml.__defineMacro("\\Um@default", "{\\;\\mathrm{m}}");
temml.__defineMacro("\\Um@a", "{\\mathrm{m}}");
temml.__defineMacro("\\UN@default", "{\\;\\mathrm{N}}");
temml.__defineMacro("\\UN@a", "{\\mathrm{N}}");
temml.__defineMacro("\\UO@default", "{\\;\\Omega}");
temml.__defineMacro("\\UO@a", "{\\Omega}");
temml.__defineMacro("\\Us@default", "{\\;\\mathrm{s}}");
temml.__defineMacro("\\Us@a", "{\\mathrm{s}}");
temml.__defineMacro("\\UT@default", "{\\;\\mathrm{T}}");
temml.__defineMacro("\\UT@a", "{\\mathrm{T}}");
temml.__defineMacro("\\Uu@default", "{\\;\\mathrm{u}}");
temml.__defineMacro("\\Uu@a", "{\\mathrm{u}}");
temml.__defineMacro("\\UV@default", "{\\;\\mathrm{V}}");
temml.__defineMacro("\\UV@a", "{\\mathrm{V}}");
temml.__defineMacro("\\UW@default", "{\\;\\mathrm{W}}");
temml.__defineMacro("\\UW@a", "{\\mathrm{W}}");
temml.__defineMacro("\\Uh@default", "{\\;\\mathrm{h}}");
temml.__defineMacro("\\Uh@a", "{\\mathrm{h}}");
temml.__defineMacro("\\Ut@default", "{\\;\\mathrm{t}}");
temml.__defineMacro("\\Ut@a", "{\\mathrm{t}}");

temml.preprocessLatexUnits = preprocessLatexUnits;